[package]
name = "circlepod-protocol"
version = "0.1.0"
description = "Circlepod Protocol"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "circlepod_protocol"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.6.0"
