[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[clusters.localnet]
circlepod_protocol = "JAJx8YQ9VzLMPVxWGSWyzJBZhdhp8HH43y1g27PJttWH"
staking_lockup = "DLePRXaXLQo3PDZVH6jV1mBzTvAfmry5kN7R8WKiDV9L"
staking_registry = "FHmHR9PWcLb7NjLeKUMTkvKwkr4TLVVzERZErcfqzQSx"