[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[clusters.localnet]
staking_lockup = "HLVA2NmjGBsoKCwmGZg1zAYXFxMhKXRMf7V28RexGpcR"
staking_registry = "4wcKkwjthmfHd7CZNsCxnyZoEiujBLbDvJ7jDFjqoiKm"

[clusters.devnet]
staking_lockup = "HLVA2NmjGBsoKCwmGZg1zAYXFxMhKXRMf7V28RexGpcR"
staking_registry = "4wcKkwjthmfHd7CZNsCxnyZoEiujBLbDvJ7jDFjqoiKm"